### PR TITLE
Relax Poison version requirement

### PR DESCRIPTION
**Pull request by jasonwebster**
The public API hasn't changed enough to matter here. There's no reason to stay on 1.2.x as far as I can tell.

### CODE REVIEW

**Comment by jasonwebster** [comment]
The build is going to fail, but it does on `master` too...

**Comment by johnhamelink** [comment]
Any reason why this hasn't been merged

**Comment by b-murphy** [comment]
+1 on merge

**Comment by HashNuke** [comment]
Even hackney requirement needs to be relaxed.

**Pull request merged**
